In [3]:
import sys
sys.path.append('..')  # so we can import from models/

from models.bsm import bsm_price
import numpy as np

In [4]:
# Benchmark 1: Single option (canonical case)
price = bsm_price(S=100, K=100, T=1.0, r=0.05, sigma=0.20, option_type='call')
print(f"Single ATM call: {price}")

# Benchmark 2: Vector of strikes
strikes = np.array([80, 90, 100, 110, 120])
prices = bsm_price(S=100, K=strikes, T=1.0, r=0.05, sigma=0.20, option_type='call')
print(f"Vector of strikes: {prices}")
print(f"Shape: {prices.shape}")

# Benchmark 3: 2D grid (the real test of broadcasting)
strikes = np.array([90, 100, 110])         # shape (3,)
maturities = np.array([[0.25], [0.5], [1.0], [2.0]])  # shape (4, 1)
grid = bsm_price(S=100, K=strikes, T=maturities, r=0.05, sigma=0.20, option_type='call')
print(f"\nGrid shape: {grid.shape}")
print(f"Grid:\n{grid}")

Single ATM call: 10.450583572185565
Vector of strikes: [24.58883544 16.69944841 10.45058357  6.04008813  3.24747742]
Shape: (5,)

Grid shape: (4, 3)
Grid:
[[11.67008669  4.61499713  1.19113166]
 [13.49851748  6.88872858  2.90647132]
 [16.69944841 10.45058357  6.04008813]
 [22.03338001 16.12677972 11.45545587]]


In [11]:
# Benchmark 4: Put-Call Parity 2D grid 
C = bsm_price(S=100, K=strikes, T=maturities, r=0.05, sigma=0.20, option_type='call')
P = bsm_price(S=100, K=strikes, T=maturities, r=0.05, sigma=0.20, option_type='put')
parity_residual = C - P - 100 + strikes * np.exp(-0.05 * maturities)
MAR = np.max(np.abs(pc_grid))
print(f"\nGrid shape: {pc_grid.shape}")
print(f"Grid:\n{pc_grid}")
print(f"\nMax Absolute Residual: {MAR}")
assert MAR <= 1e-10



Grid shape: (4, 3)
Grid:
[[ 0.00000000e+00  0.00000000e+00  1.42108547e-14]
 [-1.42108547e-14  0.00000000e+00  1.42108547e-14]
 [ 0.00000000e+00  0.00000000e+00 -1.42108547e-14]
 [ 1.42108547e-14  1.42108547e-14  0.00000000e+00]]

Max Absolute Residual: 1.4210854715202004e-14
